version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      NGINX_HOST: ${APP_BASE_URL}
      NGINX_PORT: 80
    ports:
      - "80:80"
    depends_on:
      - app
      - db
    volumes:
      - ./docker/conf/nginx/project.conf:/etc/nginx/conf.d/project.template
      - ./app:/var/www
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/project.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  app:
    build:
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_UID}
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - ./docker/conf/php/project.ini:/usr/local/etc/php/conf.d/project.ini
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dump/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db-data/:/var/lib/mysql/
      - ./docker/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DOCKER_PG_PORT:-3306}:3306